import { AngularAppEngine, createRequestHandler } from '@angular/ssr';
import { bootReport, ensureWarm, inventory, startup } from '../src/boot/startup';
import { featuredSlice } from '../src/app/core/catalog-data';
import type { ServerRenderContext } from '../src/app/core/telemetry';

/**
 * Alternative SSR entry point, for platforms that are not Node servers.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THIS FILE IS THE COST OF THE COMPARISON.
 *
 * On Cloud Run, the `src/server.ts` generated by `ng add @angular/ssr` runs
 * unchanged: it is an ordinary HTTP server inside an ordinary container.
 *
 * Lambda has no HTTP server. It has a function that receives a JSON event and
 * returns another one. That requires:
 *
 *   1. this entry point, using the web-standard API (`AngularAppEngine`)
 *      instead of the Node API (`AngularNodeAppEngine`);
 *   2. a separate build configuration in angular.json, because `ssr.entry`
 *      now points somewhere else;
 *   3. `handler.mjs`, translating AWS events to and from web Request/Response;
 *   4. an infrastructure template (SAM) to wire up the Function URL and
 *      permissions.
 *
 * Four artifacts that Cloud Run did not ask for.
 * ─────────────────────────────────────────────────────────────────────────
 */

/**
 * The same SSRF protection configured in `src/server.ts` — and it has to be
 * repeated here. Each entry point builds its own engine instance, so
 * forgetting this line makes every request return 400 after deployment. It is
 * exactly the kind of detail that two entry points charge you for and one
 * would not.
 *
 * A Function URL domain is only known after the first deploy, which makes
 * environment-based configuration effectively mandatory on this platform.
 */
const allowedHosts = (process.env['ALLOWED_HOSTS'] ?? '')
  .split(',')
  .map((host) => host.trim())
  .filter(Boolean);

const angularApp = new AngularAppEngine({ allowedHosts });

const instanceId = Math.random().toString(16).slice(2, 10);
const bootTime = Date.now();

let requestCount = 0;
let firstRenderMs: number | null = null;
let warmRenderCount = 0;
let warmRenderTotalMs = 0;

/**
 * The startup sequence is shared with `src/server.ts` — and so is the problem.
 *
 * Lambda has no equivalent of `--min-instances`: provisioned concurrency exists
 * but is billed by the hour whether or not anything calls the function, and an
 * execution environment is reclaimed on the platform's schedule, not yours.
 * The same {@link startup} work therefore gets paid more often here, which is
 * the honest reason cold starts have a worse reputation on Lambda than on
 * Cloud Run — not the runtime, the lifecycle.
 */
export const reqHandler = createRequestHandler(async (request: Request) => {
  const arrivalMs = Date.now();
  const requestNumber = ++requestCount;

  await startup;
  await ensureWarm();

  const handleStartMs = Date.now();
  const url = new URL(request.url);
  const productId = /^\/product\/([^/]+)\/?$/.exec(url.pathname)?.[1];
  const query = url.searchParams.get('q') ?? '';
  const category = url.searchParams.get('category') ?? '';

  const context: ServerRenderContext = {
    telemetry: {
      instanceId,
      requestNumber,
      coldStart: requestNumber === 1,
      uptimeMs: handleStartMs - bootTime,
      inFlight: 1,
      peakInFlight: 1,
      port: '',
      service: process.env['AWS_LAMBDA_FUNCTION_NAME'] ?? '',
      revision: process.env['AWS_LAMBDA_FUNCTION_VERSION'] ?? '',
      // Lambda is not Cloud Run, and the UI should not pretend otherwise.
      platform: 'local',
      renderDelayMs: 0,
      handleStartMs,
      boot: bootReport(),
      warmupWaitMs: handleStartMs - arrivalMs,
      firstRenderMs,
      warmRenderAvgMs: warmRenderCount ? Math.round(warmRenderTotalMs / warmRenderCount) : null,
      warmSamples: warmRenderCount,
    },
    catalog:
      url.pathname === '/' && (query.trim() || category.trim())
        ? inventory().search({ query, category, limit: 24 })
        : featuredSlice(),
    product: productId ? (inventory().byId(decodeURIComponent(productId)) ?? null) : null,
  };

  /**
   * Unlike `AngularNodeAppEngine`, this `handle` speaks web-standard `Request`
   * and `Response` — the same objects `fetch` uses. That is what allows the app
   * to run on Lambda, Cloudflare Workers, Deno, or any non-Node runtime.
   */
  const response = await angularApp.handle(request, context);

  const renderMs = Date.now() - handleStartMs;
  if (requestNumber === 1) {
    firstRenderMs = renderMs;
  } else {
    warmRenderCount++;
    warmRenderTotalMs += renderMs;
  }

  return response ?? new Response('Not found', { status: 404 });
});
