import { AngularAppEngine, createRequestHandler } from '@angular/ssr';

/**
 * Alternative SSR entry point, for platforms that are not Node servers.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THIS FILE IS THE COST OF THE COMPARISON.
 *
 * On Cloud Run, the `src/server.ts` generated by `ng add @angular/ssr` runs
 * unchanged: it is an ordinary HTTP server inside an ordinary container.
 *
 * Lambda has no HTTP server. It has a function that receives a JSON event and
 * returns another one. That requires:
 *
 *   1. this entry point, using the web-standard API (`AngularAppEngine`)
 *      instead of the Node API (`AngularNodeAppEngine`);
 *   2. a separate build configuration in angular.json, because `ssr.entry`
 *      now points somewhere else;
 *   3. `handler.mjs`, translating AWS events to and from web Request/Response;
 *   4. an infrastructure template (SAM) to wire up the Function URL and
 *      permissions.
 *
 * Four artifacts that Cloud Run did not ask for.
 * ─────────────────────────────────────────────────────────────────────────
 */

/**
 * The same SSRF protection configured in `src/server.ts` — and it has to be
 * repeated here. Each entry point builds its own engine instance, so
 * forgetting this line makes every request return 400 after deployment. It is
 * exactly the kind of detail that two entry points charge you for and one
 * would not.
 *
 * A Function URL domain is only known after the first deploy, which makes
 * environment-based configuration effectively mandatory on this platform.
 */
const allowedHosts = (process.env['ALLOWED_HOSTS'] ?? '')
  .split(',')
  .map((host) => host.trim())
  .filter(Boolean);

const angularApp = new AngularAppEngine({ allowedHosts });

/**
 * Unlike `AngularNodeAppEngine`, this `handle` speaks web-standard `Request`
 * and `Response` — the same objects `fetch` uses. That is what allows the app
 * to run on Lambda, Cloudflare Workers, Deno, or any non-Node runtime.
 */
export const reqHandler = createRequestHandler(async (request: Request) => {
  const response = await angularApp.handle(request);

  return response ?? new Response('Not found', { status: 404 });
});
